promptToReturnFromSubprocess: false
gui:
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden' | 'bold'
  border: single
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
