promptToReturnFromSubprocess: false
gui:
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden' | 'bold'
  border: single
git:
  pagers:
    - pager: delta --paging=never
    - pager: delta --paging=never --side-by-side --line-numbers
    # - externalDiffCommand: difft --color=always --display=inline --context=5
    # - externalDiffCommand: ~/.local/bin/difft --color=always --display=inline --context=5 --line-numbers=off
    # colorArg: always
