inherits = "carbonfox"

"ui.background" = { bg = "bg0" }
"ui.cursorline.primary" = { bg = "bg2" }
"ui.virtual.ruler" = { bg = "bg2" }


warning = "magenta"
error = "red"
info = "blue"
hint = "orange"

# Hard to read excluded files if "dim" is present.
# "diagnostic.unnecessary" = { modifiers = [] }

# Block doc comments, e.g '/** */' in rust. Hard to distinguish otherwise
"comment.block.documentation" = { fg = "comment", modifiers = ["dim"] }
# Line doc comments, e.g '///' in rust.
"comment.line.documentation" = { fg = "comment", modifiers = ["italic"] }

# ui.background = {}
# ui.gutter = {}
