[build]
rustc-wrapper = "sccache"
rustflags = ["-Z", "threads=8"]

[profile.release]
lto = true

[profile.dev]
opt-level = 1
codegen-backend = "cranelift"

[unstable]
codegen-backend = true

[profile.dev.package."*"]
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"] # "target-cpu=native"
